# Generated by Django 4.2.9 on 2024-01-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockfiles',
            old_name='module',
            new_name='block',
        ),
    ]
