# Generated by Django 4.2.9 on 2024-01-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('block', '0002_rename_module_blockfiles_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='module.module', verbose_name='модуль'),
            preserve_default=False,
        ),
    ]
