# Generated by Django 4.2.9 on 2024-01-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_alter_block_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'блок модуля', 'verbose_name_plural': 'блоки модуля'},
        ),
    ]
