# Generated by Django 4.2.9 on 2024-01-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0004_alter_discipline_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'навык',
                'verbose_name_plural': 'навыки',
            },
        ),
        migrations.CreateModel(
            name='SkillCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline', verbose_name='дисциплина')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_products.skill', verbose_name='навык')),
            ],
            options={
                'verbose_name': 'навык дисциплины',
                'verbose_name_plural': 'навыки дисциплины',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='disciplines',
            field=models.ManyToManyField(related_name='skills', through='skills_products.SkillCurriculum', to='discipline.discipline', verbose_name='дисциплины'),
        ),
    ]
