# Generated by Django 4.2.9 on 2024-01-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0004_alter_discipline_name'),
        ('skills_products', '0002_rename_skillcurriculum_skilldiscipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AlterUniqueTogether(
            name='skilldiscipline',
            unique_together={('skill', 'discipline')},
        ),
        migrations.CreateModel(
            name='ProductDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline', verbose_name='дисциплина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт дисциплины',
                'verbose_name_plural': 'продукты дисциплины',
                'unique_together': {('product', 'discipline')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='disciplines',
            field=models.ManyToManyField(related_name='products', through='skills_products.ProductDiscipline', to='discipline.discipline', verbose_name='дисциплины'),
        ),
    ]
