# Generated by Django 4.2.9 on 2024-01-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('main_text', models.TextField(default='', verbose_name='Основной текст')),
                ('position', models.IntegerField(blank=True, verbose_name='Позиция')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='discipline.discipline', verbose_name='Дисциплина')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module', to='discipline.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Блок программы',
                'verbose_name_plural': 'Блоки программ',
            },
        ),
        migrations.CreateModel(
            name='ModuleFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='module_files/%Y/%m/%d/', verbose_name='Файл')),
                ('position', models.IntegerField(blank=True, verbose_name='Позиция')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='module.module', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Файл блока',
                'verbose_name_plural': 'Файлы блока',
            },
        ),
    ]
