# Generated by Django 4.2.9 on 2024-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='main_text',
            field=models.TextField(blank=True, default='', verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='module',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='modulefiles',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('discipline', 'section', 'position'), name='unique_positions'),
        ),
        migrations.AddConstraint(
            model_name='modulefiles',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='unique_positions_files'),
        ),
    ]
