# Generated by Django 4.2.9 on 2024-01-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'модули'},
        ),
    ]
