# Generated by Django 4.2.9 on 2024-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел дисциплины', 'verbose_name_plural': 'Разделы дисциплин'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
