# Generated by Django 4.2.9 on 2024-01-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_module_options'),
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='modules',
            field=models.ManyToManyField(related_name='disciplines', through='discipline.DisciplineModule', to='module.module'),
        ),
    ]
