# Generated by Django 4.2.9 on 2024-01-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_alter_disciplinemodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
