# Generated by Django 4.2.9 on 2024-01-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0002_disciplinemodule_discipline_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'учебный план',
                'verbose_name_plural': 'учебные планы',
            },
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('study_period', models.IntegerField(verbose_name='срок обучения')),
            ],
            options={
                'verbose_name': 'уровень образования',
                'verbose_name_plural': 'уровни образования',
            },
        ),
        migrations.CreateModel(
            name='CurriculumDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='семестр')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculum', verbose_name='учебный план')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.discipline', verbose_name='дисциплина')),
            ],
            options={
                'verbose_name': 'дисциплина учебного плана',
                'verbose_name_plural': 'дисциплины учебного плана',
                'unique_together': {('discipline', 'curriculum', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='disciplines',
            field=models.ManyToManyField(related_name='curriculums', through='curriculum.CurriculumDiscipline', to='discipline.discipline', verbose_name='дисциплины'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='educational_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='curriculum.educationallevel', verbose_name='уровень обучения'),
        ),
    ]
